### ISSUE TITLE
解答谜题：重复做题，可能存在刷经验的问题

### ISSUE THREAD

**Issue by jjgm666** [zhangyin-github/Hunter#1]
重复成功的做同一个问题，会使得积分和经验都一直增加。
应增加成功解决问题的积分限制：如果成功解决了某一谜题，再次解决将不增加积分和经验。

**Comment by Futaba-Kotobuki** [comment]
解决不了，需要修改太多的逻辑，麻烦先提出会导致程序不正常运行的bug，谢谢。
